services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_ADDRESS=${VITE_API_URL:-http://localhost:8000}
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    entrypoint: ./scripts/init_db.sh
    ports:
      - 8000:8000
    networks:
      - network
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://user:password@postgres:5432/madr_db}
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - network
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: madr_db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
